# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnippetsCli < Formula
  desc "Clean and simple code sharing"
  homepage "https://github.com/stevedylandev/snippets-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.3/snippets-cli_Darwin_x86_64.tar.gz"
      sha256 "7a818cf8f82015d24da9829f0f7758d41c42ada2c951771999dd7b5fed513e67"

      def install
        bin.install "snip"
      end
    end
    on_arm do
      url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.3/snippets-cli_Darwin_arm64.tar.gz"
      sha256 "514c714cb815a0f9308dc91bf215951923f6f4defef49ad4c078328c0aab2773"

      def install
        bin.install "snip"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.3/snippets-cli_Linux_x86_64.tar.gz"
        sha256 "72fba6a2c2e7de84b76db7bbcb286cb4229c1d7a788cdf2708fdc62cafa648e2"

        def install
          bin.install "snip"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.3/snippets-cli_Linux_arm64.tar.gz"
        sha256 "80e0c536a2306bd7d4403ccd7f9516471006961eb7febb2fa3fad963e440a172"

        def install
          bin.install "snip"
        end
      end
    end
  end
end
