# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnippetsCli < Formula
  desc "Clean and simple code sharing"
  homepage "https://github.com/stevedylandev/snippets-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.1/snippets-cli_Darwin_x86_64.tar.gz"
      sha256 "f2dfa9dcde032ce5ffaa6df09fef90d3ff93500852173de327441841f6d354a0"

      def install
        bin.install "snippets-cli"
      end
    end
    on_arm do
      url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.1/snippets-cli_Darwin_arm64.tar.gz"
      sha256 "b70dc1c953359b0dcf7f41822341284eb4a44cc665944bb32fc84b787898df1e"

      def install
        bin.install "snippets-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.1/snippets-cli_Linux_x86_64.tar.gz"
        sha256 "407eb961a1f249d0048b1262366b6594296c0b5be54c19c50261fc2351057783"

        def install
          bin.install "snippets-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.1/snippets-cli_Linux_arm64.tar.gz"
        sha256 "fcc95390dadf0d1a8401f86634df083fb8a2f20564c381059224a9e175b54bf9"

        def install
          bin.install "snippets-cli"
        end
      end
    end
  end
end
