# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnippetsCli < Formula
  desc "Clean and simple code sharing"
  homepage "https://github.com/stevedylandev/snippets-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.0/snippets-cli_Darwin_x86_64.tar.gz"
      sha256 "5d991dfd790182662e8efc09f7e0294770dbe3400852fc198840c34d35b25192"

      def install
        bin.install "snippets-cli"
      end
    end
    on_arm do
      url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.0/snippets-cli_Darwin_arm64.tar.gz"
      sha256 "2cd03db0d7350aa07c7460a32befa6f03c8fe15d5f0c984f2799602a2006b1eb"

      def install
        bin.install "snippets-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.0/snippets-cli_Linux_x86_64.tar.gz"
        sha256 "c05da4fef150ed6a0bdb4f6397d1bf5c8b2cdfe585a2efe8b9b369e9dbcc1522"

        def install
          bin.install "snippets-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/snippets-cli/releases/download/v0.1.0/snippets-cli_Linux_arm64.tar.gz"
        sha256 "718f165e5b9901b6bcf14a3650e06322361926a95c15789cc27e0cd757da9887"

        def install
          bin.install "snippets-cli"
        end
      end
    end
  end
end
